name: Publish SDK Package

on:
  push:
    branches:
      - main
    paths:
      - "sdk/**"
      - ".github/workflows/publish-sdk.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          scope: "@stockspro"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Setup npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "@stockspro:registry=https://registry.npmjs.org/" >> .npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --no-git-checks
